// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobOT/Generics.proto

package OTDB;

public final class Generics {
	private Generics() {
	}

	public static void registerAllExtensions(
			com.google.protobuf.ExtensionRegistry registry) {
	}

	public interface String_InternalPBOrBuilder
			extends com.google.protobuf.MessageOrBuilder {

		// optional string value = 1;
		boolean hasValue();

		String getValue();
	}

	public static final class String_InternalPB extends
			com.google.protobuf.GeneratedMessage
			implements String_InternalPBOrBuilder {
		// Use String_InternalPB.newBuilder() to construct.
		private String_InternalPB(Builder builder) {
			super(builder);
		}

		private String_InternalPB(boolean noInit) {
		}

		private static final String_InternalPB defaultInstance;

		public static String_InternalPB getDefaultInstance() {
			return defaultInstance;
		}

		@Override
		public String_InternalPB getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor
				getDescriptor() {
			return OTDB.Generics.internal_static_OTDB_String_InternalPB_descriptor;
		}

		@Override
		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
				internalGetFieldAccessorTable() {
			return OTDB.Generics.internal_static_OTDB_String_InternalPB_fieldAccessorTable;
		}

		private int bitField0_;
		// optional string value = 1;
		public static final int VALUE_FIELD_NUMBER = 1;
		private java.lang.Object value_;

		@Override
		public boolean hasValue() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		@Override
		public String getValue() {
			java.lang.Object ref = value_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs =
						(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					value_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getValueBytes() {
			java.lang.Object ref = value_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b =
						com.google.protobuf.ByteString.copyFromUtf8((String) ref);
				value_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private void initFields() {
			value_ = "";
		}

		private byte memoizedIsInitialized = -1;

		@Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeBytes(1, getValueBytes());
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		@Override
		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream
						.computeBytesSize(1, getValueBytes());
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static OTDB.Generics.String_InternalPB parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static OTDB.Generics.String_InternalPB parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static OTDB.Generics.String_InternalPB parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static OTDB.Generics.String_InternalPB parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static OTDB.Generics.String_InternalPB parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static OTDB.Generics.String_InternalPB parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static OTDB.Generics.String_InternalPB parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static OTDB.Generics.String_InternalPB parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static OTDB.Generics.String_InternalPB parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static OTDB.Generics.String_InternalPB parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		@Override
		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(OTDB.Generics.String_InternalPB prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		@Override
		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder>
				implements OTDB.Generics.String_InternalPBOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor
					getDescriptor() {
				return OTDB.Generics.internal_static_OTDB_String_InternalPB_descriptor;
			}

			@Override
			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
					internalGetFieldAccessorTable() {
				return OTDB.Generics.internal_static_OTDB_String_InternalPB_fieldAccessorTable;
			}

			// Construct using OTDB.Generics.String_InternalPB.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}

			private static Builder create() {
				return new Builder();
			}

			@Override
			public Builder clear() {
				super.clear();
				value_ = "";
				bitField0_ = (bitField0_ & ~0x00000001);
				return this;
			}

			@Override
			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			@Override
			public com.google.protobuf.Descriptors.Descriptor
					getDescriptorForType() {
				return OTDB.Generics.String_InternalPB.getDescriptor();
			}

			@Override
			public OTDB.Generics.String_InternalPB getDefaultInstanceForType() {
				return OTDB.Generics.String_InternalPB.getDefaultInstance();
			}

			@Override
			public OTDB.Generics.String_InternalPB build() {
				OTDB.Generics.String_InternalPB result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private OTDB.Generics.String_InternalPB buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				OTDB.Generics.String_InternalPB result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(
							result).asInvalidProtocolBufferException();
				}
				return result;
			}

			@Override
			public OTDB.Generics.String_InternalPB buildPartial() {
				OTDB.Generics.String_InternalPB result = new OTDB.Generics.String_InternalPB(this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.value_ = value_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			@Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof OTDB.Generics.String_InternalPB) {
					return mergeFrom((OTDB.Generics.String_InternalPB) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(OTDB.Generics.String_InternalPB other) {
				if (other == OTDB.Generics.String_InternalPB.getDefaultInstance())
					return this;
				if (other.hasValue()) {
					setValue(other.getValue());
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			@Override
			public final boolean isInitialized() {
				return true;
			}

			@Override
			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields =
						com.google.protobuf.UnknownFieldSet.newBuilder(
								this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 10: {
						bitField0_ |= 0x00000001;
						value_ = input.readBytes();
						break;
					}
					}
				}
			}

			private int bitField0_;

			// optional string value = 1;
			private java.lang.Object value_ = "";

			@Override
			public boolean hasValue() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			@Override
			public String getValue() {
				java.lang.Object ref = value_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
					value_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			public Builder setValue(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				value_ = value;
				onChanged();
				return this;
			}

			public Builder clearValue() {
				bitField0_ = (bitField0_ & ~0x00000001);
				value_ = getDefaultInstance().getValue();
				onChanged();
				return this;
			}

			void setValue(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000001;
				value_ = value;
				onChanged();
			}

			// @@protoc_insertion_point(builder_scope:OTDB.String_InternalPB)
		}

		static {
			defaultInstance = new String_InternalPB(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:OTDB.String_InternalPB)
	}

	public interface KeyValue_InternalPBOrBuilder
			extends com.google.protobuf.MessageOrBuilder {

		// optional string key = 1;
		boolean hasKey();

		String getKey();

		// optional string value = 2;
		boolean hasValue();

		String getValue();
	}

	public static final class KeyValue_InternalPB extends
			com.google.protobuf.GeneratedMessage
			implements KeyValue_InternalPBOrBuilder {
		// Use KeyValue_InternalPB.newBuilder() to construct.
		private KeyValue_InternalPB(Builder builder) {
			super(builder);
		}

		private KeyValue_InternalPB(boolean noInit) {
		}

		private static final KeyValue_InternalPB defaultInstance;

		public static KeyValue_InternalPB getDefaultInstance() {
			return defaultInstance;
		}

		@Override
		public KeyValue_InternalPB getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor
				getDescriptor() {
			return OTDB.Generics.internal_static_OTDB_KeyValue_InternalPB_descriptor;
		}

		@Override
		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
				internalGetFieldAccessorTable() {
			return OTDB.Generics.internal_static_OTDB_KeyValue_InternalPB_fieldAccessorTable;
		}

		private int bitField0_;
		// optional string key = 1;
		public static final int KEY_FIELD_NUMBER = 1;
		private java.lang.Object key_;

		@Override
		public boolean hasKey() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		@Override
		public String getKey() {
			java.lang.Object ref = key_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs =
						(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					key_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getKeyBytes() {
			java.lang.Object ref = key_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b =
						com.google.protobuf.ByteString.copyFromUtf8((String) ref);
				key_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		// optional string value = 2;
		public static final int VALUE_FIELD_NUMBER = 2;
		private java.lang.Object value_;

		@Override
		public boolean hasValue() {
			return ((bitField0_ & 0x00000002) == 0x00000002);
		}

		@Override
		public String getValue() {
			java.lang.Object ref = value_;
			if (ref instanceof String) {
				return (String) ref;
			} else {
				com.google.protobuf.ByteString bs =
						(com.google.protobuf.ByteString) ref;
				String s = bs.toStringUtf8();
				if (com.google.protobuf.Internal.isValidUtf8(bs)) {
					value_ = s;
				}
				return s;
			}
		}

		private com.google.protobuf.ByteString getValueBytes() {
			java.lang.Object ref = value_;
			if (ref instanceof String) {
				com.google.protobuf.ByteString b =
						com.google.protobuf.ByteString.copyFromUtf8((String) ref);
				value_ = b;
				return b;
			} else {
				return (com.google.protobuf.ByteString) ref;
			}
		}

		private void initFields() {
			key_ = "";
			value_ = "";
		}

		private byte memoizedIsInitialized = -1;

		@Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeBytes(1, getKeyBytes());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				output.writeBytes(2, getValueBytes());
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		@Override
		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream
						.computeBytesSize(1, getKeyBytes());
			}
			if (((bitField0_ & 0x00000002) == 0x00000002)) {
				size += com.google.protobuf.CodedOutputStream
						.computeBytesSize(2, getValueBytes());
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static OTDB.Generics.KeyValue_InternalPB parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static OTDB.Generics.KeyValue_InternalPB parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static OTDB.Generics.KeyValue_InternalPB parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static OTDB.Generics.KeyValue_InternalPB parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static OTDB.Generics.KeyValue_InternalPB parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static OTDB.Generics.KeyValue_InternalPB parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static OTDB.Generics.KeyValue_InternalPB parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static OTDB.Generics.KeyValue_InternalPB parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static OTDB.Generics.KeyValue_InternalPB parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static OTDB.Generics.KeyValue_InternalPB parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		@Override
		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(OTDB.Generics.KeyValue_InternalPB prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		@Override
		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder>
				implements OTDB.Generics.KeyValue_InternalPBOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor
					getDescriptor() {
				return OTDB.Generics.internal_static_OTDB_KeyValue_InternalPB_descriptor;
			}

			@Override
			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
					internalGetFieldAccessorTable() {
				return OTDB.Generics.internal_static_OTDB_KeyValue_InternalPB_fieldAccessorTable;
			}

			// Construct using OTDB.Generics.KeyValue_InternalPB.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}

			private static Builder create() {
				return new Builder();
			}

			@Override
			public Builder clear() {
				super.clear();
				key_ = "";
				bitField0_ = (bitField0_ & ~0x00000001);
				value_ = "";
				bitField0_ = (bitField0_ & ~0x00000002);
				return this;
			}

			@Override
			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			@Override
			public com.google.protobuf.Descriptors.Descriptor
					getDescriptorForType() {
				return OTDB.Generics.KeyValue_InternalPB.getDescriptor();
			}

			@Override
			public OTDB.Generics.KeyValue_InternalPB getDefaultInstanceForType() {
				return OTDB.Generics.KeyValue_InternalPB.getDefaultInstance();
			}

			@Override
			public OTDB.Generics.KeyValue_InternalPB build() {
				OTDB.Generics.KeyValue_InternalPB result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private OTDB.Generics.KeyValue_InternalPB buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				OTDB.Generics.KeyValue_InternalPB result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(
							result).asInvalidProtocolBufferException();
				}
				return result;
			}

			@Override
			public OTDB.Generics.KeyValue_InternalPB buildPartial() {
				OTDB.Generics.KeyValue_InternalPB result = new OTDB.Generics.KeyValue_InternalPB(this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.key_ = key_;
				if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
					to_bitField0_ |= 0x00000002;
				}
				result.value_ = value_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			@Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof OTDB.Generics.KeyValue_InternalPB) {
					return mergeFrom((OTDB.Generics.KeyValue_InternalPB) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(OTDB.Generics.KeyValue_InternalPB other) {
				if (other == OTDB.Generics.KeyValue_InternalPB.getDefaultInstance())
					return this;
				if (other.hasKey()) {
					setKey(other.getKey());
				}
				if (other.hasValue()) {
					setValue(other.getValue());
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			@Override
			public final boolean isInitialized() {
				return true;
			}

			@Override
			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields =
						com.google.protobuf.UnknownFieldSet.newBuilder(
								this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 10: {
						bitField0_ |= 0x00000001;
						key_ = input.readBytes();
						break;
					}
					case 18: {
						bitField0_ |= 0x00000002;
						value_ = input.readBytes();
						break;
					}
					}
				}
			}

			private int bitField0_;

			// optional string key = 1;
			private java.lang.Object key_ = "";

			@Override
			public boolean hasKey() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			@Override
			public String getKey() {
				java.lang.Object ref = key_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
					key_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			public Builder setKey(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				key_ = value;
				onChanged();
				return this;
			}

			public Builder clearKey() {
				bitField0_ = (bitField0_ & ~0x00000001);
				key_ = getDefaultInstance().getKey();
				onChanged();
				return this;
			}

			void setKey(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000001;
				key_ = value;
				onChanged();
			}

			// optional string value = 2;
			private java.lang.Object value_ = "";

			@Override
			public boolean hasValue() {
				return ((bitField0_ & 0x00000002) == 0x00000002);
			}

			@Override
			public String getValue() {
				java.lang.Object ref = value_;
				if (!(ref instanceof String)) {
					String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
					value_ = s;
					return s;
				} else {
					return (String) ref;
				}
			}

			public Builder setValue(String value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000002;
				value_ = value;
				onChanged();
				return this;
			}

			public Builder clearValue() {
				bitField0_ = (bitField0_ & ~0x00000002);
				value_ = getDefaultInstance().getValue();
				onChanged();
				return this;
			}

			void setValue(com.google.protobuf.ByteString value) {
				bitField0_ |= 0x00000002;
				value_ = value;
				onChanged();
			}

			// @@protoc_insertion_point(builder_scope:OTDB.KeyValue_InternalPB)
		}

		static {
			defaultInstance = new KeyValue_InternalPB(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:OTDB.KeyValue_InternalPB)
	}

	public interface StringMap_InternalPBOrBuilder
			extends com.google.protobuf.MessageOrBuilder {

		// repeated .OTDB.KeyValue_InternalPB node = 1;
		java.util.List<OTDB.Generics.KeyValue_InternalPB>
				getNodeList();

		OTDB.Generics.KeyValue_InternalPB getNode(int index);

		int getNodeCount();

		java.util.List<? extends OTDB.Generics.KeyValue_InternalPBOrBuilder>
				getNodeOrBuilderList();

		OTDB.Generics.KeyValue_InternalPBOrBuilder getNodeOrBuilder(
				int index);
	}

	public static final class StringMap_InternalPB extends
			com.google.protobuf.GeneratedMessage
			implements StringMap_InternalPBOrBuilder {
		// Use StringMap_InternalPB.newBuilder() to construct.
		private StringMap_InternalPB(Builder builder) {
			super(builder);
		}

		private StringMap_InternalPB(boolean noInit) {
		}

		private static final StringMap_InternalPB defaultInstance;

		public static StringMap_InternalPB getDefaultInstance() {
			return defaultInstance;
		}

		@Override
		public StringMap_InternalPB getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor
				getDescriptor() {
			return OTDB.Generics.internal_static_OTDB_StringMap_InternalPB_descriptor;
		}

		@Override
		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
				internalGetFieldAccessorTable() {
			return OTDB.Generics.internal_static_OTDB_StringMap_InternalPB_fieldAccessorTable;
		}

		// repeated .OTDB.KeyValue_InternalPB node = 1;
		public static final int NODE_FIELD_NUMBER = 1;
		private java.util.List<OTDB.Generics.KeyValue_InternalPB> node_;

		@Override
		public java.util.List<OTDB.Generics.KeyValue_InternalPB> getNodeList() {
			return node_;
		}

		@Override
		public java.util.List<? extends OTDB.Generics.KeyValue_InternalPBOrBuilder>
				getNodeOrBuilderList() {
			return node_;
		}

		@Override
		public int getNodeCount() {
			return node_.size();
		}

		@Override
		public OTDB.Generics.KeyValue_InternalPB getNode(int index) {
			return node_.get(index);
		}

		@Override
		public OTDB.Generics.KeyValue_InternalPBOrBuilder getNodeOrBuilder(
				int index) {
			return node_.get(index);
		}

		private void initFields() {
			node_ = java.util.Collections.emptyList();
		}

		private byte memoizedIsInitialized = -1;

		@Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			for (int i = 0; i < node_.size(); i++) {
				output.writeMessage(1, node_.get(i));
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		@Override
		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			for (int i = 0; i < node_.size(); i++) {
				size += com.google.protobuf.CodedOutputStream
						.computeMessageSize(1, node_.get(i));
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static OTDB.Generics.StringMap_InternalPB parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static OTDB.Generics.StringMap_InternalPB parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static OTDB.Generics.StringMap_InternalPB parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static OTDB.Generics.StringMap_InternalPB parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static OTDB.Generics.StringMap_InternalPB parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static OTDB.Generics.StringMap_InternalPB parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static OTDB.Generics.StringMap_InternalPB parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static OTDB.Generics.StringMap_InternalPB parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static OTDB.Generics.StringMap_InternalPB parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static OTDB.Generics.StringMap_InternalPB parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		@Override
		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(OTDB.Generics.StringMap_InternalPB prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		@Override
		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder>
				implements OTDB.Generics.StringMap_InternalPBOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor
					getDescriptor() {
				return OTDB.Generics.internal_static_OTDB_StringMap_InternalPB_descriptor;
			}

			@Override
			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
					internalGetFieldAccessorTable() {
				return OTDB.Generics.internal_static_OTDB_StringMap_InternalPB_fieldAccessorTable;
			}

			// Construct using OTDB.Generics.StringMap_InternalPB.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
					getNodeFieldBuilder();
				}
			}

			private static Builder create() {
				return new Builder();
			}

			@Override
			public Builder clear() {
				super.clear();
				if (nodeBuilder_ == null) {
					node_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
				} else {
					nodeBuilder_.clear();
				}
				return this;
			}

			@Override
			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			@Override
			public com.google.protobuf.Descriptors.Descriptor
					getDescriptorForType() {
				return OTDB.Generics.StringMap_InternalPB.getDescriptor();
			}

			@Override
			public OTDB.Generics.StringMap_InternalPB getDefaultInstanceForType() {
				return OTDB.Generics.StringMap_InternalPB.getDefaultInstance();
			}

			@Override
			public OTDB.Generics.StringMap_InternalPB build() {
				OTDB.Generics.StringMap_InternalPB result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private OTDB.Generics.StringMap_InternalPB buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				OTDB.Generics.StringMap_InternalPB result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(
							result).asInvalidProtocolBufferException();
				}
				return result;
			}

			@Override
			public OTDB.Generics.StringMap_InternalPB buildPartial() {
				OTDB.Generics.StringMap_InternalPB result = new OTDB.Generics.StringMap_InternalPB(this);
				int from_bitField0_ = bitField0_;
				if (nodeBuilder_ == null) {
					if (((bitField0_ & 0x00000001) == 0x00000001)) {
						node_ = java.util.Collections.unmodifiableList(node_);
						bitField0_ = (bitField0_ & ~0x00000001);
					}
					result.node_ = node_;
				} else {
					result.node_ = nodeBuilder_.build();
				}
				onBuilt();
				return result;
			}

			@Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof OTDB.Generics.StringMap_InternalPB) {
					return mergeFrom((OTDB.Generics.StringMap_InternalPB) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(OTDB.Generics.StringMap_InternalPB other) {
				if (other == OTDB.Generics.StringMap_InternalPB.getDefaultInstance())
					return this;
				if (nodeBuilder_ == null) {
					if (!other.node_.isEmpty()) {
						if (node_.isEmpty()) {
							node_ = other.node_;
							bitField0_ = (bitField0_ & ~0x00000001);
						} else {
							ensureNodeIsMutable();
							node_.addAll(other.node_);
						}
						onChanged();
					}
				} else {
					if (!other.node_.isEmpty()) {
						if (nodeBuilder_.isEmpty()) {
							nodeBuilder_.dispose();
							nodeBuilder_ = null;
							node_ = other.node_;
							bitField0_ = (bitField0_ & ~0x00000001);
							nodeBuilder_ =
									com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
											getNodeFieldBuilder() : null;
						} else {
							nodeBuilder_.addAllMessages(other.node_);
						}
					}
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			@Override
			public final boolean isInitialized() {
				return true;
			}

			@Override
			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields =
						com.google.protobuf.UnknownFieldSet.newBuilder(
								this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 10: {
						OTDB.Generics.KeyValue_InternalPB.Builder subBuilder = OTDB.Generics.KeyValue_InternalPB
								.newBuilder();
						input.readMessage(subBuilder, extensionRegistry);
						addNode(subBuilder.buildPartial());
						break;
					}
					}
				}
			}

			private int bitField0_;

			// repeated .OTDB.KeyValue_InternalPB node = 1;
			private java.util.List<OTDB.Generics.KeyValue_InternalPB> node_ =
					java.util.Collections.emptyList();

			private void ensureNodeIsMutable() {
				if (!((bitField0_ & 0x00000001) == 0x00000001)) {
					node_ = new java.util.ArrayList<OTDB.Generics.KeyValue_InternalPB>(node_);
					bitField0_ |= 0x00000001;
				}
			}

			private com.google.protobuf.RepeatedFieldBuilder<OTDB.Generics.KeyValue_InternalPB, OTDB.Generics.KeyValue_InternalPB.Builder, OTDB.Generics.KeyValue_InternalPBOrBuilder> nodeBuilder_;

			@Override
			public java.util.List<OTDB.Generics.KeyValue_InternalPB> getNodeList() {
				if (nodeBuilder_ == null) {
					return java.util.Collections.unmodifiableList(node_);
				} else {
					return nodeBuilder_.getMessageList();
				}
			}

			@Override
			public int getNodeCount() {
				if (nodeBuilder_ == null) {
					return node_.size();
				} else {
					return nodeBuilder_.getCount();
				}
			}

			@Override
			public OTDB.Generics.KeyValue_InternalPB getNode(int index) {
				if (nodeBuilder_ == null) {
					return node_.get(index);
				} else {
					return nodeBuilder_.getMessage(index);
				}
			}

			public Builder setNode(
					int index, OTDB.Generics.KeyValue_InternalPB value) {
				if (nodeBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureNodeIsMutable();
					node_.set(index, value);
					onChanged();
				} else {
					nodeBuilder_.setMessage(index, value);
				}
				return this;
			}

			public Builder setNode(
					int index, OTDB.Generics.KeyValue_InternalPB.Builder builderForValue) {
				if (nodeBuilder_ == null) {
					ensureNodeIsMutable();
					node_.set(index, builderForValue.build());
					onChanged();
				} else {
					nodeBuilder_.setMessage(index, builderForValue.build());
				}
				return this;
			}

			public Builder addNode(OTDB.Generics.KeyValue_InternalPB value) {
				if (nodeBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureNodeIsMutable();
					node_.add(value);
					onChanged();
				} else {
					nodeBuilder_.addMessage(value);
				}
				return this;
			}

			public Builder addNode(
					int index, OTDB.Generics.KeyValue_InternalPB value) {
				if (nodeBuilder_ == null) {
					if (value == null) {
						throw new NullPointerException();
					}
					ensureNodeIsMutable();
					node_.add(index, value);
					onChanged();
				} else {
					nodeBuilder_.addMessage(index, value);
				}
				return this;
			}

			public Builder addNode(
					OTDB.Generics.KeyValue_InternalPB.Builder builderForValue) {
				if (nodeBuilder_ == null) {
					ensureNodeIsMutable();
					node_.add(builderForValue.build());
					onChanged();
				} else {
					nodeBuilder_.addMessage(builderForValue.build());
				}
				return this;
			}

			public Builder addNode(
					int index, OTDB.Generics.KeyValue_InternalPB.Builder builderForValue) {
				if (nodeBuilder_ == null) {
					ensureNodeIsMutable();
					node_.add(index, builderForValue.build());
					onChanged();
				} else {
					nodeBuilder_.addMessage(index, builderForValue.build());
				}
				return this;
			}

			public Builder addAllNode(
					java.lang.Iterable<? extends OTDB.Generics.KeyValue_InternalPB> values) {
				if (nodeBuilder_ == null) {
					ensureNodeIsMutable();
					super.addAll(values, node_);
					onChanged();
				} else {
					nodeBuilder_.addAllMessages(values);
				}
				return this;
			}

			public Builder clearNode() {
				if (nodeBuilder_ == null) {
					node_ = java.util.Collections.emptyList();
					bitField0_ = (bitField0_ & ~0x00000001);
					onChanged();
				} else {
					nodeBuilder_.clear();
				}
				return this;
			}

			public Builder removeNode(int index) {
				if (nodeBuilder_ == null) {
					ensureNodeIsMutable();
					node_.remove(index);
					onChanged();
				} else {
					nodeBuilder_.remove(index);
				}
				return this;
			}

			public OTDB.Generics.KeyValue_InternalPB.Builder getNodeBuilder(
					int index) {
				return getNodeFieldBuilder().getBuilder(index);
			}

			@Override
			public OTDB.Generics.KeyValue_InternalPBOrBuilder getNodeOrBuilder(
					int index) {
				if (nodeBuilder_ == null) {
					return node_.get(index);
				} else {
					return nodeBuilder_.getMessageOrBuilder(index);
				}
			}

			@Override
			public java.util.List<? extends OTDB.Generics.KeyValue_InternalPBOrBuilder>
					getNodeOrBuilderList() {
				if (nodeBuilder_ != null) {
					return nodeBuilder_.getMessageOrBuilderList();
				} else {
					return java.util.Collections.unmodifiableList(node_);
				}
			}

			public OTDB.Generics.KeyValue_InternalPB.Builder addNodeBuilder() {
				return getNodeFieldBuilder().addBuilder(
						OTDB.Generics.KeyValue_InternalPB.getDefaultInstance());
			}

			public OTDB.Generics.KeyValue_InternalPB.Builder addNodeBuilder(
					int index) {
				return getNodeFieldBuilder().addBuilder(
						index, OTDB.Generics.KeyValue_InternalPB.getDefaultInstance());
			}

			public java.util.List<OTDB.Generics.KeyValue_InternalPB.Builder>
					getNodeBuilderList() {
				return getNodeFieldBuilder().getBuilderList();
			}

			private com.google.protobuf.RepeatedFieldBuilder<
					OTDB.Generics.KeyValue_InternalPB, OTDB.Generics.KeyValue_InternalPB.Builder, OTDB.Generics.KeyValue_InternalPBOrBuilder>
					getNodeFieldBuilder() {
				if (nodeBuilder_ == null) {
					nodeBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
							OTDB.Generics.KeyValue_InternalPB, OTDB.Generics.KeyValue_InternalPB.Builder, OTDB.Generics.KeyValue_InternalPBOrBuilder>(
									node_,
									((bitField0_ & 0x00000001) == 0x00000001),
									getParentForChildren(),
									isClean());
					node_ = null;
				}
				return nodeBuilder_;
			}

			// @@protoc_insertion_point(builder_scope:OTDB.StringMap_InternalPB)
		}

		static {
			defaultInstance = new StringMap_InternalPB(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:OTDB.StringMap_InternalPB)
	}

	public interface Blob_InternalPBOrBuilder
			extends com.google.protobuf.MessageOrBuilder {

		// optional bytes value = 1;
		boolean hasValue();

		com.google.protobuf.ByteString getValue();
	}

	public static final class Blob_InternalPB extends
			com.google.protobuf.GeneratedMessage
			implements Blob_InternalPBOrBuilder {
		// Use Blob_InternalPB.newBuilder() to construct.
		private Blob_InternalPB(Builder builder) {
			super(builder);
		}

		private Blob_InternalPB(boolean noInit) {
		}

		private static final Blob_InternalPB defaultInstance;

		public static Blob_InternalPB getDefaultInstance() {
			return defaultInstance;
		}

		@Override
		public Blob_InternalPB getDefaultInstanceForType() {
			return defaultInstance;
		}

		public static final com.google.protobuf.Descriptors.Descriptor
				getDescriptor() {
			return OTDB.Generics.internal_static_OTDB_Blob_InternalPB_descriptor;
		}

		@Override
		protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
				internalGetFieldAccessorTable() {
			return OTDB.Generics.internal_static_OTDB_Blob_InternalPB_fieldAccessorTable;
		}

		private int bitField0_;
		// optional bytes value = 1;
		public static final int VALUE_FIELD_NUMBER = 1;
		private com.google.protobuf.ByteString value_;

		@Override
		public boolean hasValue() {
			return ((bitField0_ & 0x00000001) == 0x00000001);
		}

		@Override
		public com.google.protobuf.ByteString getValue() {
			return value_;
		}

		private void initFields() {
			value_ = com.google.protobuf.ByteString.EMPTY;
		}

		private byte memoizedIsInitialized = -1;

		@Override
		public final boolean isInitialized() {
			byte isInitialized = memoizedIsInitialized;
			if (isInitialized != -1)
				return isInitialized == 1;

			memoizedIsInitialized = 1;
			return true;
		}

		@Override
		public void writeTo(com.google.protobuf.CodedOutputStream output)
				throws java.io.IOException {
			getSerializedSize();
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				output.writeBytes(1, value_);
			}
			getUnknownFields().writeTo(output);
		}

		private int memoizedSerializedSize = -1;

		@Override
		public int getSerializedSize() {
			int size = memoizedSerializedSize;
			if (size != -1)
				return size;

			size = 0;
			if (((bitField0_ & 0x00000001) == 0x00000001)) {
				size += com.google.protobuf.CodedOutputStream
						.computeBytesSize(1, value_);
			}
			size += getUnknownFields().getSerializedSize();
			memoizedSerializedSize = size;
			return size;
		}

		private static final long serialVersionUID = 0L;

		@java.lang.Override
		protected java.lang.Object writeReplace()
				throws java.io.ObjectStreamException {
			return super.writeReplace();
		}

		public static OTDB.Generics.Blob_InternalPB parseFrom(
				com.google.protobuf.ByteString data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static OTDB.Generics.Blob_InternalPB parseFrom(
				com.google.protobuf.ByteString data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static OTDB.Generics.Blob_InternalPB parseFrom(byte[] data)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data).buildParsed();
		}

		public static OTDB.Generics.Blob_InternalPB parseFrom(
				byte[] data,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws com.google.protobuf.InvalidProtocolBufferException {
			return newBuilder().mergeFrom(data, extensionRegistry)
					.buildParsed();
		}

		public static OTDB.Generics.Blob_InternalPB parseFrom(java.io.InputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static OTDB.Generics.Blob_InternalPB parseFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static OTDB.Generics.Blob_InternalPB parseDelimitedFrom(java.io.InputStream input)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static OTDB.Generics.Blob_InternalPB parseDelimitedFrom(
				java.io.InputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			Builder builder = newBuilder();
			if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
				return builder.buildParsed();
			} else {
				return null;
			}
		}

		public static OTDB.Generics.Blob_InternalPB parseFrom(
				com.google.protobuf.CodedInputStream input)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input).buildParsed();
		}

		public static OTDB.Generics.Blob_InternalPB parseFrom(
				com.google.protobuf.CodedInputStream input,
				com.google.protobuf.ExtensionRegistryLite extensionRegistry)
				throws java.io.IOException {
			return newBuilder().mergeFrom(input, extensionRegistry)
					.buildParsed();
		}

		public static Builder newBuilder() {
			return Builder.create();
		}

		@Override
		public Builder newBuilderForType() {
			return newBuilder();
		}

		public static Builder newBuilder(OTDB.Generics.Blob_InternalPB prototype) {
			return newBuilder().mergeFrom(prototype);
		}

		@Override
		public Builder toBuilder() {
			return newBuilder(this);
		}

		@java.lang.Override
		protected Builder newBuilderForType(
				com.google.protobuf.GeneratedMessage.BuilderParent parent) {
			Builder builder = new Builder(parent);
			return builder;
		}

		public static final class Builder extends
				com.google.protobuf.GeneratedMessage.Builder<Builder>
				implements OTDB.Generics.Blob_InternalPBOrBuilder {
			public static final com.google.protobuf.Descriptors.Descriptor
					getDescriptor() {
				return OTDB.Generics.internal_static_OTDB_Blob_InternalPB_descriptor;
			}

			@Override
			protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
					internalGetFieldAccessorTable() {
				return OTDB.Generics.internal_static_OTDB_Blob_InternalPB_fieldAccessorTable;
			}

			// Construct using OTDB.Generics.Blob_InternalPB.newBuilder()
			private Builder() {
				maybeForceBuilderInitialization();
			}

			private Builder(BuilderParent parent) {
				super(parent);
				maybeForceBuilderInitialization();
			}

			private void maybeForceBuilderInitialization() {
				if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
				}
			}

			private static Builder create() {
				return new Builder();
			}

			@Override
			public Builder clear() {
				super.clear();
				value_ = com.google.protobuf.ByteString.EMPTY;
				bitField0_ = (bitField0_ & ~0x00000001);
				return this;
			}

			@Override
			public Builder clone() {
				return create().mergeFrom(buildPartial());
			}

			@Override
			public com.google.protobuf.Descriptors.Descriptor
					getDescriptorForType() {
				return OTDB.Generics.Blob_InternalPB.getDescriptor();
			}

			@Override
			public OTDB.Generics.Blob_InternalPB getDefaultInstanceForType() {
				return OTDB.Generics.Blob_InternalPB.getDefaultInstance();
			}

			@Override
			public OTDB.Generics.Blob_InternalPB build() {
				OTDB.Generics.Blob_InternalPB result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(result);
				}
				return result;
			}

			private OTDB.Generics.Blob_InternalPB buildParsed()
					throws com.google.protobuf.InvalidProtocolBufferException {
				OTDB.Generics.Blob_InternalPB result = buildPartial();
				if (!result.isInitialized()) {
					throw newUninitializedMessageException(
							result).asInvalidProtocolBufferException();
				}
				return result;
			}

			@Override
			public OTDB.Generics.Blob_InternalPB buildPartial() {
				OTDB.Generics.Blob_InternalPB result = new OTDB.Generics.Blob_InternalPB(this);
				int from_bitField0_ = bitField0_;
				int to_bitField0_ = 0;
				if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
					to_bitField0_ |= 0x00000001;
				}
				result.value_ = value_;
				result.bitField0_ = to_bitField0_;
				onBuilt();
				return result;
			}

			@Override
			public Builder mergeFrom(com.google.protobuf.Message other) {
				if (other instanceof OTDB.Generics.Blob_InternalPB) {
					return mergeFrom((OTDB.Generics.Blob_InternalPB) other);
				} else {
					super.mergeFrom(other);
					return this;
				}
			}

			public Builder mergeFrom(OTDB.Generics.Blob_InternalPB other) {
				if (other == OTDB.Generics.Blob_InternalPB.getDefaultInstance())
					return this;
				if (other.hasValue()) {
					setValue(other.getValue());
				}
				this.mergeUnknownFields(other.getUnknownFields());
				return this;
			}

			@Override
			public final boolean isInitialized() {
				return true;
			}

			@Override
			public Builder mergeFrom(
					com.google.protobuf.CodedInputStream input,
					com.google.protobuf.ExtensionRegistryLite extensionRegistry)
					throws java.io.IOException {
				com.google.protobuf.UnknownFieldSet.Builder unknownFields =
						com.google.protobuf.UnknownFieldSet.newBuilder(
								this.getUnknownFields());
				while (true) {
					int tag = input.readTag();
					switch (tag) {
					case 0:
						this.setUnknownFields(unknownFields.build());
						onChanged();
						return this;
					default: {
						if (!parseUnknownField(input, unknownFields,
								extensionRegistry, tag)) {
							this.setUnknownFields(unknownFields.build());
							onChanged();
							return this;
						}
						break;
					}
					case 10: {
						bitField0_ |= 0x00000001;
						value_ = input.readBytes();
						break;
					}
					}
				}
			}

			private int bitField0_;

			// optional bytes value = 1;
			private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;

			@Override
			public boolean hasValue() {
				return ((bitField0_ & 0x00000001) == 0x00000001);
			}

			@Override
			public com.google.protobuf.ByteString getValue() {
				return value_;
			}

			public Builder setValue(com.google.protobuf.ByteString value) {
				if (value == null) {
					throw new NullPointerException();
				}
				bitField0_ |= 0x00000001;
				value_ = value;
				onChanged();
				return this;
			}

			public Builder clearValue() {
				bitField0_ = (bitField0_ & ~0x00000001);
				value_ = getDefaultInstance().getValue();
				onChanged();
				return this;
			}

			// @@protoc_insertion_point(builder_scope:OTDB.Blob_InternalPB)
		}

		static {
			defaultInstance = new Blob_InternalPB(true);
			defaultInstance.initFields();
		}

		// @@protoc_insertion_point(class_scope:OTDB.Blob_InternalPB)
	}

	private static com.google.protobuf.Descriptors.Descriptor internal_static_OTDB_String_InternalPB_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_OTDB_String_InternalPB_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.Descriptor internal_static_OTDB_KeyValue_InternalPB_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_OTDB_KeyValue_InternalPB_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.Descriptor internal_static_OTDB_StringMap_InternalPB_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_OTDB_StringMap_InternalPB_fieldAccessorTable;
	private static com.google.protobuf.Descriptors.Descriptor internal_static_OTDB_Blob_InternalPB_descriptor;
	private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_OTDB_Blob_InternalPB_fieldAccessorTable;

	public static com.google.protobuf.Descriptors.FileDescriptor
			getDescriptor() {
		return descriptor;
	}

	private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
	static {
		java.lang.String[] descriptorData = {
				"\n\027protobOT/Generics.proto\022\004OTDB\"\"\n\021Strin" +
						"g_InternalPB\022\r\n\005value\030\001 \001(\t\"1\n\023KeyValue_" +
						"InternalPB\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\"?" +
						"\n\024StringMap_InternalPB\022\'\n\004node\030\001 \003(\0132\031.O" +
						"TDB.KeyValue_InternalPB\" \n\017Blob_Internal" +
						"PB\022\r\n\005value\030\001 \001(\014"
		};
		com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
				new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
					@Override
					public com.google.protobuf.ExtensionRegistry assignDescriptors(
							com.google.protobuf.Descriptors.FileDescriptor root) {
						descriptor = root;
						internal_static_OTDB_String_InternalPB_descriptor =
								getDescriptor().getMessageTypes().get(0);
						internal_static_OTDB_String_InternalPB_fieldAccessorTable = new
								com.google.protobuf.GeneratedMessage.FieldAccessorTable(
										internal_static_OTDB_String_InternalPB_descriptor,
										new java.lang.String[] { "Value", },
										OTDB.Generics.String_InternalPB.class,
										OTDB.Generics.String_InternalPB.Builder.class);
						internal_static_OTDB_KeyValue_InternalPB_descriptor =
								getDescriptor().getMessageTypes().get(1);
						internal_static_OTDB_KeyValue_InternalPB_fieldAccessorTable = new
								com.google.protobuf.GeneratedMessage.FieldAccessorTable(
										internal_static_OTDB_KeyValue_InternalPB_descriptor,
										new java.lang.String[] { "Key", "Value", },
										OTDB.Generics.KeyValue_InternalPB.class,
										OTDB.Generics.KeyValue_InternalPB.Builder.class);
						internal_static_OTDB_StringMap_InternalPB_descriptor =
								getDescriptor().getMessageTypes().get(2);
						internal_static_OTDB_StringMap_InternalPB_fieldAccessorTable = new
								com.google.protobuf.GeneratedMessage.FieldAccessorTable(
										internal_static_OTDB_StringMap_InternalPB_descriptor,
										new java.lang.String[] { "Node", },
										OTDB.Generics.StringMap_InternalPB.class,
										OTDB.Generics.StringMap_InternalPB.Builder.class);
						internal_static_OTDB_Blob_InternalPB_descriptor =
								getDescriptor().getMessageTypes().get(3);
						internal_static_OTDB_Blob_InternalPB_fieldAccessorTable = new
								com.google.protobuf.GeneratedMessage.FieldAccessorTable(
										internal_static_OTDB_Blob_InternalPB_descriptor,
										new java.lang.String[] { "Value", },
										OTDB.Generics.Blob_InternalPB.class,
										OTDB.Generics.Blob_InternalPB.Builder.class);
						return null;
					}
				};
		com.google.protobuf.Descriptors.FileDescriptor
				.internalBuildGeneratedFileFrom(descriptorData,
						new com.google.protobuf.Descriptors.FileDescriptor[] {
						}, assigner);
	}

	// @@protoc_insertion_point(outer_class_scope)
}
